# 04_Figures_v2/functions/02_data_paths_and_loaders.R
# Pipeline step 02: input paths + data loaders. A v2 snapshot of the validated
# 04_Figures/shared config engine — adds the old-combined-results -> brief
# contrast naming map plus the canonical read-only input paths. Reads existing
# pipeline outputs only; never re-runs 01-03. Derived-data caches (rat_gene_sets,
# fgsea cache, localization table) are still read single-sourced from
# 04_Figures/shared so they never drift; only the engine CODE lives here.

source(here::here("04_Figures_v2", "functions", "01_style_palettes_theme.R")) # palettes, groups, contrasts, thresholds

# Brief contrast naming
# The limma model is already fit; 03_combined_results.csv carries 5 contrasts
# under the OLD names. Map them to the brief's names for display; algebra identical.
CONTRAST_DISPLAY_MAP <- c(
  CTLvMITO      = "Transplant", # Mito - Ctl
  CTLvPHE       = "Disease", # PHE - Ctl
  PHEvPHE_MITO  = "Rescue", # PHE_Mito - PHE
  Interaction   = "Interaction", # orthogonal 2x2
  MITOvPHE_MITO = "Secondary" # PHE_Mito - Mito
)

# Verbatim math labels (Unicode minus U+2212) keyed by OLD name.
CONTRAST_MATH_BRIEF <- c(
  CTLvMITO = "Mito − Ctl",
  CTLvPHE = "PHE − Ctl",
  PHEvPHE_MITO = "PHE_Mito − PHE",
  Interaction = "(PHE_Mito − Mito) − (PHE − Ctl)",
  MITOvPHE_MITO = "PHE_Mito − Mito",
  Interaction_Phe = "PHE_Mito − 2·Mito + Ctl"
)

# Short brief display name for tight strips.
contrast_brief <- function(old_name) {
  out <- CONTRAST_DISPLAY_MAP[old_name]
  ifelse(is.na(out), old_name, unname(out))
}

# Role name for a contrast (Disease / Transplant / Rescue / Interaction / Secondary).
role_label <- contrast_brief

fig05_base <- function(fig) here::here("04_Figures", fig)

# Canonical pipeline inputs (read-only; never regenerated by 04_Figures).
# comb    = non-imputed DE (the reported/canonical analysis — feeds F02–F05).
# imp_rds = the imputed matrix used ONLY where a gap-free matrix is required (F01 PCA, F06 mfuzz).
#   missForest is used here: with left-censored MNAR missingness it tracks the non-imputed
#   effect sizes most closely (Spearman 0.98–0.99) and does not manufacture DEPs, unlike imp4p.
#   PCA is imputation-invariant either way (Procrustes ~0.999); the choice matters only for the
#   ~1% missing-heavy genes that move the F06 Group_Pi variant.
P05 <- list(
  comb    = here::here("03_DEP", "a_non_imputed", "c_data", "combined_results_pi.csv"),
  imp_rds = here::here("02_Normalization", "imputation", "c_data", "DAList_imputed_missforest.rds")
)

# The DEP table is now long (one row per protein x contrast). Figures expect the
# old wide layout (logFC_CTLvPHE, pi_score_CTLvPHE, ...); contrast names are
# unchanged, so widen without recoding.
load_combined_wide <- function(path = P05$comb) {
  readr::read_csv(path, show_col_types = FALSE) |>
    tidyr::pivot_wider(
      id_cols     = c(uniprot_id, gene, protein, description),
      names_from  = contrast,
      values_from = c(logFC, t, P.Value, adj.P.Val, pi_score, sig_pi),
      names_glue  = "{.value}_{contrast}"
    )
}

# Print + return a tidy contrast table (sanity check on source-time).
fig05_contrast_table <- function() {
  old <- names(CONTRAST_DISPLAY_MAP)
  data.frame(
    old_name = old,
    brief_name = unname(CONTRAST_DISPLAY_MAP[old]),
    definition = unname(CONTRAST_MATH_BRIEF[old]),
    role = unname(H9C2_CONTRAST_ROLES[old]),
    inferential = TRUE,
    row.names = NULL, stringsAsFactors = FALSE
  ) |>
    rbind(data.frame(
      old_name = "(derived)", brief_name = "Interaction_Phe",
      definition = unname(CONTRAST_MATH_BRIEF["Interaction_Phe"]),
      role = "Exploratory", inferential = FALSE, stringsAsFactors = FALSE
    ))
}
