# 04_Figures/shared/config.R
# Thin shared layer for the consolidated 04_Figures stage. Sources the validated
# 04_Figures/shared engines (style, palettes, mitocarta, comparison panels) and
# adds the only two things 04_Figures needs on top:
#   (1) CONTRAST_DISPLAY_MAP — old combined-results column names -> brief names.
#   (2) derive_interaction_phe() — descriptive (non-inferential) Interaction_Phe.
#
# Reads from existing pipeline outputs only; never re-runs 01-03.

# Source the canonical shared engines (do NOT duplicate)
source(here::here("04_Figures", "shared", "style.R"))   # palettes, groups, contrasts, thresholds

# Brief contrast naming
# The limma model is already fit; 03_combined_results.csv carries 5 contrasts
# under the OLD names. Map them to the brief's names for display; algebra identical.
CONTRAST_DISPLAY_MAP <- c(
  CTLvMITO      = "Transplant_Mito",      # Mito - Ctl       (transplant in healthy cells)
  CTLvPHE       = "Disease_Phe",          # PHE - Ctl        (α1-adrenergic hypertrophy proxy)
  PHEvPHE_MITO  = "Rescue_Mito+Phe",      # PHE_Mito - PHE   (transplant under disease)
  Interaction   = "Interaction_Mito",     # canonical orthogonal 2x2 interaction
  MITOvPHE_MITO = "Secondary_PheInMito"   # PHE_Mito - Mito  (PHE effect in transplanted cells)
)

# Verbatim math labels (Unicode minus U+2212) keyed by OLD name.
CONTRAST_MATH_BRIEF <- c(
  CTLvMITO      = "Mito − Ctl",
  CTLvPHE       = "PHE − Ctl",
  PHEvPHE_MITO  = "PHE_Mito − PHE",
  Interaction   = "(PHE_Mito − Mito) − (PHE − Ctl)",
  MITOvPHE_MITO = "PHE_Mito − Mito",
  Interaction_Phe = "PHE_Mito − 2·Mito + Ctl"
)

# Plain-language meaning keyed by OLD name (+ derived Interaction_Phe).
CONTRAST_MEANING_BRIEF <- c(
  CTLvMITO        = "Mitochondrial transplant effect in healthy cells",
  CTLvPHE         = "In-vitro α1-adrenergic hypertrophy (PHE): cardiomyocyte-only proxy for RV-HF; does not model pressure overload, fibrosis, vasculature, or neurohumoral activation",
  PHEvPHE_MITO    = "Mitochondrial transplant effect under PHE disease (rescue)",
  Interaction     = "Non-additivity of PHE and mito transplant (orthogonal 2x2)",
  MITOvPHE_MITO   = "PHE effect within mito-transplanted cells",
  Interaction_Phe = "Exploratory / descriptive only — non-orthogonal, no inference"
)

# Short brief display name for tight strips.
contrast_brief <- function(old_name) {
  out <- CONTRAST_DISPLAY_MAP[old_name]
  ifelse(is.na(out), old_name, unname(out))
}

# Brief-named core set for the headline figures (orthogonal contrasts only).
BRIEF_CORE_OLD <- c("CTLvMITO", "CTLvPHE", "PHEvPHE_MITO", "Interaction")

# Interaction_Phe: descriptive deriver
# Interaction_Phe = (PHE_Mito - Mito) - (Mito - Ctl) = PHE_Mito - 2*Mito + Ctl
#                 = logFC_MITOvPHE_MITO - logFC_CTLvMITO   (both already in CSV)
# EXPLORATORY ONLY: logFC magnitude/direction is meaningful, but it double-counts
# the Mito group (coeffs 1, -2, 0, 1 for Ctl, Mito, PHE, PHE_Mito) and is
# NON-ORTHOGONAL, so no SE/p/pi/FDR is produced. Never use as the formal
# interaction test (that is Interaction_Mito).
derive_interaction_phe <- function(comb) {
  needed <- c("logFC_MITOvPHE_MITO", "logFC_CTLvMITO")
  miss <- setdiff(needed, names(comb))
  if (length(miss) > 0L)
    stop("derive_interaction_phe: combined results missing ", paste(miss, collapse = ", "))
  comb$logFC_MITOvPHE_MITO - comb$logFC_CTLvMITO
}

# Paths
fig05_base <- function(fig) here::here("04_Figures", fig)

# Canonical pipeline inputs (read-only; never regenerated by 04_Figures).
P05 <- list(
  comb      = here::here("03_DEP", "a_non_imputed", "c_data", "combined_results_pi.csv"),
  dep_xlsx  = here::here("03_DEP", "a_non_imputed", "c_data", "results.xlsx"),
  imp_rds   = here::here("02_Normalization", "imputation", "c_data", "DAList_imputed_imp4p.rds"),
  wgcna_net = here::here("04_Figures", "F05_modules", "c_data", "wgcna_network.rds")
)

# The DEP table is now long (one row per protein x contrast). Figures expect the
# old wide layout (logFC_CTLvPHE, pi_score_CTLvPHE, ...); contrast names are
# unchanged, so widen without recoding.
load_combined_wide <- function(path = P05$comb) {
  readr::read_csv(path, show_col_types = FALSE) |>
    tidyr::pivot_wider(
      id_cols     = c(uniprot_id, gene, protein, description),
      names_from  = contrast,
      values_from = c(logFC, t, P.Value, adj.P.Val, pi_score, sig_pi),
      names_glue  = "{.value}_{contrast}")
}

# Print + return a tidy contrast table (sanity check on source-time).
fig05_contrast_table <- function() {
  old <- names(CONTRAST_DISPLAY_MAP)
  data.frame(
    old_name   = old,
    brief_name = unname(CONTRAST_DISPLAY_MAP[old]),
    definition = unname(CONTRAST_MATH_BRIEF[old]),
    role       = unname(H9C2_CONTRAST_ROLES[old]),
    inferential = TRUE,
    row.names = NULL, stringsAsFactors = FALSE
  ) |>
    rbind(data.frame(
      old_name = "(derived)", brief_name = "Interaction_Phe",
      definition = unname(CONTRAST_MATH_BRIEF["Interaction_Phe"]),
      role = "Exploratory", inferential = FALSE, stringsAsFactors = FALSE))
}
