# Input paths, data loaders, and the old-combined-results -> brief contrast
# naming map. Reads existing 01-03 pipeline outputs only; never re-runs them.

source(here::here("04_Figures", "functions", "01_style_palettes_theme.R"))

# Brief contrast naming
# The limma model is already fit; 03_combined_results.csv carries 5 contrasts
# under the OLD names. Map them to the brief's names for display; algebra identical.
CONTRAST_DISPLAY_MAP <- c(
  CTLvMITO      = "Transplant", # Mito - Ctl
  CTLvPHE       = "Disease", # PHE - Ctl
  PHEvPHE_MITO  = "Rescue", # PHE_Mito - PHE
  Interaction   = "Interaction", # orthogonal 2x2
  MITOvPHE_MITO = "Secondary" # PHE_Mito - Mito
)

# Verbatim math labels (Unicode minus U+2212) keyed by OLD name, built from the
# condition display labels so a relabel flows through here automatically.
CONTRAST_MATH_BRIEF <- local({
  g <- H9C2_GROUP_LABELS
  c(
    CTLvMITO = sprintf("%s − %s", g[["Mito"]], g[["Ctl"]]),
    CTLvPHE = sprintf("%s − %s", g[["PHE"]], g[["Ctl"]]),
    PHEvPHE_MITO = sprintf("%s − %s", g[["PHE_Mito"]], g[["PHE"]]),
    Interaction = sprintf(
      "(%s − %s) − (%s − %s)",
      g[["PHE_Mito"]], g[["Mito"]], g[["PHE"]], g[["Ctl"]]
    ),
    MITOvPHE_MITO = sprintf("%s − %s", g[["PHE_Mito"]], g[["Mito"]])
  )
})

# Short brief display name for tight strips.
contrast_brief <- function(old_name) {
  out <- CONTRAST_DISPLAY_MAP[old_name]
  ifelse(is.na(out), old_name, unname(out))
}

# Eigengene-limma contrasts in terms of the Group design columns (Ctl/Mito/PHE/
# PHE_Mito). Same three the brief names; used by makeContrasts on module eigengenes.
ME_CONTRASTS <- c(
  Disease    = "PHE - Ctl",
  Transplant = "Mito - Ctl",
  Rescue     = "PHE_Mito - PHE"
)

# A protein carries a real rat symbol when `gene` is not an Ensembl id or a bare
# UniProt accession (the fallback for the ~30/4806 without an official symbol).
is_real_symbol <- function(gene) {
  !is.na(gene) & nzchar(gene) & !grepl("^ENS", gene) &
    !grepl("^[A-Z][0-9][A-Z0-9]{3}[0-9]([A-Z0-9]{4})?$", gene)
}

# Canonical pipeline inputs (read-only; never regenerated by 04_Figures).
# comb    = non-imputed DE (the reported/canonical analysis — feeds F02–F03).
# imp_rds = the imputed matrix used ONLY where a gap-free matrix is required (F01 PCA, F06 mfuzz).
#   missForest is used here: with left-censored MNAR missingness it tracks the non-imputed
#   effect sizes most closely (Spearman 0.98–0.99) and does not manufacture DEPs, unlike imp4p.
#   PCA is imputation-invariant either way (Procrustes ~0.999); the choice matters only for the
#   ~1% missing-heavy genes that move the F06 Group_Pi variant.
P05 <- list(
  comb    = here::here("03_DEP", "a_non_imputed", "c_data", "combined_results_pi.csv"),
  imp_rds = here::here("02_Normalization", "imputation", "c_data", "DAList_imputed_missforest.rds")
)

# The DEP table is now long (one row per protein x contrast). Figures expect the
# old wide layout (logFC_CTLvPHE, pi_score_CTLvPHE, ...); contrast names are
# unchanged, so widen without recoding.
load_combined_wide <- function(path = P05$comb) {
  readr::read_csv(path, show_col_types = FALSE) |>
    tidyr::pivot_wider(
      id_cols     = c(uniprot_id, gene, protein, description),
      names_from  = contrast,
      values_from = c(logFC, t, P.Value, adj.P.Val, pi_score, sig_pi),
      names_glue  = "{.value}_{contrast}"
    )
}
