# Mito-keyword regex: single source of truth for the mito lens.

# Mito-keyword regex applied to Hallmark/Reactome/KEGG/GO-Slim pathway names so
# mito-relevant non-MitoCarta sets are flagged alongside the MITOCARTA_* sets.
MITO_PATHWAY_REGEX <- paste(
  "MITOCHOND",
  "OXPHOS|OXIDATIVE_PHOSPH",
  "AEROBIC_RESPIRATION|ELECTRON_TRANSPORT_CHAIN|RESPIRATORY_(CHAIN|ELECTRON)",
  "CITRATE_CYCLE|TRICARBOXYLIC|KREBS_CYCLE",
  "MITOPHAG",
  "MITO.+FISSION|FISSION.+MITO|MITO.+FUSION|FUSION.+MITO",
  "CRISTAE",
  "PROTEIN_IMPORT_INTO_MITO|MITOCH.+PROTEIN_IMPORT",
  "MICOS",
  "BETA_OXIDATION",
  "CARDIOLIPIN",
  "CARNITINE",
  "HEME_BIO|HEME_METAB",
  "FE_S_CLUSTER|IRON_SULFUR_CLUSTER",
  "PYRUVATE_(METABOLISM|DEHYDROGENASE)",
  "KETONE_(BODY|BIOSYNTH|METAB)",
  "ONE_CARBON_(POOL|METABOL)|GLYCINE_CLEAVAGE",
  "MITORIBOSOM",
  "NADH_DEHYDROGENASE|SUCCINATE_DEHYDROGENASE|CYTOCHROME_C_OXIDASE|ATP_SYNTHASE",
  "INTRINSIC_(APOPTOTIC|PATHWAY_FOR_APOPTOSIS)",
  "RELEASE_OF_CYTOCHROME_C|CYTOCHROME_COMPLEX_ASSEMBLY",
  sep = "|"
)
