#!/usr/bin/env Rscript
# Build the GO:BP/CC/MF rat gene sets the F03 module ORA adds on top of the
# canonical collection.
#   Output: 04_Figures/shared/c_data/rat_go_bpccmf_sets.rds
#
# PROVENANCE: MSigDB C5 GO sets, Rattus norvegicus, pinned to the installed
# msigdbr version. Regenerated by this script, not committed. See the README
# (Gene Sets and Provenance).

suppressPackageStartupMessages(library(msigdbr))

OUT <- here::here("04_Figures", "shared", "c_data", "rat_go_bpccmf_sets.rds")
dir.create(dirname(OUT), recursive = TRUE, showWarnings = FALSE)

go_sets <- do.call(c, lapply(c("GO:BP", "GO:CC", "GO:MF"), function(sub) {
  m5 <- msigdbr(species = "Rattus norvegicus", collection = "C5", subcollection = sub)
  split(m5$gene_symbol, m5$gs_name)
}))

saveRDS(go_sets, OUT)
cat(sprintf("Saved %s (%d sets, msigdbr %s)\n", OUT, length(go_sets), packageVersion("msigdbr")))
